name: "Build: Image Pipeline"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ vars.ubuntu_version }}
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Local Source Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - run: |
          apt-get update
          apt-get install -y lsb-release curl unzip
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      - run: |
          which pip3 || curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          which pip3 || python3 get-pip.py --user
          
      - run: pip install --user ansible
      
      - name: Run Ansible Playbook
        id: build
        run: $(python -m site --user-base)/bin/ansible-playbook apt-cache.yml

      - name: upload packages
        run: aws s3 cp /var/cache/apt/archives s3://${{ vars.apt_cache_bucket }}/${{ vars.apt_cache_key }} --recursive
