name: "Build: Image Pipeline"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ vars.ubuntu_version }}
      volumes:
        - ${{ github.workspace }}/apt:/var/cache/apt/archives
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Local Source Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - run: |
          apt-get update
          apt-get install -y lsb-release
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
        
      - run: pip install --user ansible
      
      - name: Run Ansible Playbook
        id: build
        run: $(python -m site --user-base)/bin/ansible-playbook apt-cache.yml

      - name: upload packages
        run: aws s3 cp /var/cache/apt/archives s3://${{ vars.apt_cache_bucket }}/${{ vars.apt_cache_key }} --recursive
